apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-agent
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  autoregister.properties: |-
    agent.auto.register.key={{ .Values.agent.autoRegisterKey | quote }}
